#ifndef __AUTOGENRATED_VARIANT_MODEL_HPP__
#define __AUTOGENRATED_VARIANT_MODEL_HPP__

#include <mc/particles/particles_container.hpp>
#include <mc/particles/particle_model.hpp>
#include <variant>

@INCLUDES@

namespace AutoGenerated
{
  using ContainerVariant = std::variant<@VARIANT_TYPE@>;
} // namespace AutoGenerated


#endif //__AUTOGENRATED_VARIANT_MODEL_HPP__