test_query = executable(
    'test_query',
    'test_query.cpp',
    dependencies: [mixture_dependency],
)

test('test_query_species', test_query)

test_specie_table = executable(
    'test_specie_table',
    'test_specie_table.cpp',
    dependencies: [mixture_dependency],
)

test('test_specie_table', test_specie_table)