fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file:.clang-format]
      # - id: clang-tidy
      #   args: [./apps/*]
  - repo:
      https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: ["--config", ".ruff.toml"]
        #args: [--fix]
        # Run the formatter.
      - id: ruff-format
        args: ["--config", ".ruff.toml"]
