# version: "3.6"
services:
  app:
    image: biocma_mcst
    build: ./devutils/docker
    container_name: biocma_mcst__dev
    volumes:
      - ./devutils/docker/runtime_container:/app
      - ./apps/:/app/apps
      - ./subprojects:/app/subprojects
      - ./cma_data:/app/cma_data
      - ./modules:/app/modules
      - ./.clang-format:/app/.clang-format
      - ./.clang-tidy:/app/.clang-tidy
      - ./meson.build:/app/meson.build
      - ./meson_options.txt:/app/meson_options.txt


