# version: "3.6"
services:
  biocma_app:
    &biocma_app
    # image: bcasale/bio_cma_mc_runtime
    build: 
      context: ./devutils/docker
      dockerfile: Dockerfile.debian
    container_name: biocma_mcst__dev
    volumes:
      - ./devutils/docker/runtime_container:/app:Z
      - ./apps/:/app/apps:Z
      - ./subprojects:/app/subprojects:Z
      - ./cma_data/:/app/cma_data:Z
      - ./modules:/app/modules:Z
      - ./.clang-format:/app/.clang-format:Z
      - ./.clang-tidy:/app/.clang-tidy:Z
      - ./meson.build:/app/meson.build:Z
      - ./meson_options.txt:/app/meson_options.txt:Z
      - ./devutils/auto_generate:/app/devutils/auto_generate:Z
      

  biocma_app_task_test:
    <<: *biocma_app
    command:
      - /bin/sh
      - -c
      - |
        meson setup builddir --buildtype=release --reconfigure
        ninja -C builddir  test 

