# version: "3.6"
services:
  biocma_app:
    &biocma_app
    image: bcasale/bio_cma_mc_runtime
    build: ./devutils/docker
    container_name: biocma_mcst__dev
    volumes:
      - ./devutils/docker/runtime_container:/app
      - ./apps/:/app/apps
      - ./subprojects:/app/subprojects
      - ./cma_data/:/app/cma_data
      - ./modules:/app/modules
      - ./.clang-format:/app/.clang-format
      - ./.clang-tidy:/app/.clang-tidy
      - ./meson.build:/app/meson.build
      - ./meson_options.txt:/app/meson_options.txt

  biocma_app_task_test:
    <<: *biocma_app
    command:
      - /bin/sh
      - -c
      - |
        meson setup builddir --buildtype=release -Duse_cuda=true --reconfigure
        ninja -C builddir -j 1 test 

