
PWD=$(shell pwd)
TARGET ?= model

BUILD_DIR ?= builddir/test
SRC_BD ?= apps/udf_model
KOKKOS_FOLDER:=kokkos-5.1.1
CXX ?= c++

SRC := $(SRC_BD)/$(TARGET).cpp
OUT := $(BUILD_DIR)/lib$(TARGET).so

DEBUG_FLAGS := -g -O2 -DENABLE_KOKKOS_PROFILING -DDEBUG -DKOKKOS_ENABLE_DEBUG
RELEASE_FLAGS :=  -O3 -DNDEBUG

ADDITIONAL_FLAGS ?= ""

BIOMC_FLAGS := \
	-DDECLARE_EXPORT_UDF \
    -DUSE_UDF \
    -DUSE_HIGHFIVE \
    -DUSE_CEAREAL \
	-DEIGEN_NO_CUDA=1 \
	-DENABLE_KOKKOS_PROFILING  \
    $(ADDITIONAL_FLAGS)


ERROR_FLAGS := -Wall -Wextra -Wpedantic -Winvalid-pch -Wshadow \
            -Wcast-align  \
            # -Werror

FLAGS := \
	$(DEBUG_FLAGS) \
	$(BIOMC_FLAGS)\
	-fvisibility=hidden\
    -fdiagnostics-color=always \
    -D_GLIBCXX_ASSERTIONS=1 \
    -D_FILE_OFFSET_BITS=64 \
    $(ERROR_FLAGS)\
    -std=c++20 \
    -march=native -mtune=native \
    -fPIC \
    -pthread \
    -fopenmp\
	-isystem$(PWD)/subprojects/$(KOKKOS_FOLDER)/tpls/mdspan/include \
    -isystem$(PWD)/subprojects/$(KOKKOS_FOLDER)/tpls/desul/include \
    -fno-rtti




INCLUDES := \
    -I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/__CMake_build \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER) \
    -I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/__CMake_build/core/src \
    -I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/__CMake_build/containers/src \
    -I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/__CMake_build/algorithms/src \
    -I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/__CMake_build/simd/src \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/core/src \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/containers/src \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/algorithms/src \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/simd/src \
	-I$(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)\
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/tpls/desul/include \
    -I$(PWD)/subprojects/$(KOKKOS_FOLDER)/tpls/mdspan/include \
    -I$(PWD)/subprojects/kokkos_sampling/public \
    -I$(PWD)/subprojects/dynlib/public \
    -I$(PWD)/apps/udf_model \
    -I$(BUILD_DIR)/apps/udf_model \
    -I$(PWD)/apps/libs/models/public \
    -I$(PWD)/apps/libs/models/ext \
    -I$(PWD)/apps/libs/mc/public \
    -I$(PWD)/apps/libs/common/public \
	-I$(PWD)/apps/autogenerated \
    -I$(BUILD_DIR)/apps/autogenerated \




LDFLAGS := \
    -rdynamic  -Wl,--as-needed -Wl,--no-undefined -shared -fPIC \
    -Wl,-soname,lib$(TARGET).so \
    -Wl,--start-group \
    $(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/libkokkoscore.a \
    $(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/libkokkossimd.a \
    $(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/libkokkoscontainers.a \
    $(BUILD_DIR)/subprojects/$(KOKKOS_FOLDER)/libkokkosalgorithms.a \
    $(BUILD_DIR)/apps/libs/mc/libbiocma_mcst_mc.a \
    $(BUILD_DIR)/apps/libs/common/libbiocma_mcst_common.a \
    /usr/lib/x86_64-linux-gnu/libhwloc.so \
    -Wl,--end-group \
    -flto \
    -fPIC   \
    -fopenmp -pthread




.PHONY: all


OBJ = $(BUILD_DIR)/libudf_model_$(TARGET).o
LIB = $(BUILD_DIR)/libudf_model_$(TARGET).so

all: $(LIB)

$(OBJ): $(SRC)
	$(CXX) $(INCLUDES) $(FLAGS)  -o $@ -c $<

$(LIB): $(OBJ)
	$(CXX) -o $@   $^ $(LDFLAGS)
