var namespaceSimulation =
[
    [ "Feed", "namespaceSimulation_1_1Feed.html", "namespaceSimulation_1_1Feed" ],
    [ "impl", "namespaceSimulation_1_1impl.html", [
      [ "post_init_concentration_file", "namespaceSimulation_1_1impl.html#a55672c412b144c5ec1b80c5b8ee129e3", null ],
      [ "post_init_concentration_functor", "namespaceSimulation_1_1impl.html#a8621c7c62e95e65b4403bbf991f30719", null ]
    ] ],
    [ "KernelInline", "namespaceSimulation_1_1KernelInline.html", "namespaceSimulation_1_1KernelInline" ],
    [ "MassTransfer", "namespaceSimulation_1_1MassTransfer.html", "namespaceSimulation_1_1MassTransfer" ],
    [ "Dimensions", "structSimulation_1_1Dimensions.html", "structSimulation_1_1Dimensions" ],
    [ "EnvironementProperties", "structSimulation_1_1EnvironementProperties.html", "structSimulation_1_1EnvironementProperties" ],
    [ "Mixture", "classSimulation_1_1Mixture.html", "classSimulation_1_1Mixture" ],
    [ "Phase", "structSimulation_1_1Phase.html", "structSimulation_1_1Phase" ],
    [ "Probes", "classSimulation_1_1Probes.html", "classSimulation_1_1Probes" ],
    [ "ScalarInitializer", "structSimulation_1_1ScalarInitializer.html", "structSimulation_1_1ScalarInitializer" ],
    [ "ScalarSimulation", "classSimulation_1_1ScalarSimulation.html", "classSimulation_1_1ScalarSimulation" ],
    [ "SimulationException", "classSimulation_1_1SimulationException.html", "classSimulation_1_1SimulationException" ],
    [ "SimulationUnit", "classSimulation_1_1SimulationUnit.html", "classSimulation_1_1SimulationUnit" ],
    [ "Specie", "structSimulation_1_1Specie.html", "structSimulation_1_1Specie" ],
    [ "init_scalar_f_t", "namespaceSimulation.html#aaee322090ebbd49ea6c9800cd56e1b35", null ],
    [ "MapProbes", "namespaceSimulation.html#af34adaabc60487412f7551db1dc83226", null ],
    [ "ProbeAutogeneratedBuffer", "namespaceSimulation.html#a7e205e1192f8faf89b55c1d6525413f8", null ],
    [ "ProbeIterator", "namespaceSimulation.html#a1636006890c86890e493f8aeaf900ec7", null ],
    [ "SpecieTable", "namespaceSimulation.html#a8a8043f8951284c90553aeb242416f4e", null ],
    [ "ErrorCodes", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bd", [
      [ "BadConcentrationInitLiq", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdaab8d58e72483a0ad6bc6d000993cb04a", null ],
      [ "BadConcentrationInitGas", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdabaf5b84ca77154d5e3258d24429ec242", null ],
      [ "BadInitialiser", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdaea76fb02103cf3ff94efa52436f0d809", null ],
      [ "MismatchSize", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bda2dc1045efdb911eef2fc5132ae1020c1", null ]
    ] ],
    [ "ProbeType", "namespaceSimulation.html#a3844f9fb0ce2978c66af04ff0a6eece6", [
      [ "LeavingTime", "namespaceSimulation.html#a3844f9fb0ce2978c66af04ff0a6eece6a5d4158e53cb4e4db894ba87313f46de3", null ],
      [ "DivisionTime", "namespaceSimulation.html#a3844f9fb0ce2978c66af04ff0a6eece6a75d3f7cb47ebc941423743c3817cfab1", null ]
    ] ],
    [ "ScalarInitialiserType", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aa", [
      [ "Uniform", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaaf19516d11f2946f894070e92fcb56b6d", null ],
      [ "Local", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa509820290d57f333403f490dde7316f4", null ],
      [ "File", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa0b27918290ff5323bea1e3b78a9cf04e", null ],
      [ "CustomScript", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa3e7683f51af33ba15b5abc5b1907621f", null ],
      [ "FullCase", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa56b419b259c49fa979598027da1f6062", null ],
      [ "Serde", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa3aa078c74db7e488d0384999eccb7116", null ]
    ] ],
    [ "makeScalarSimulation", "namespaceSimulation.html#ae5bb8948e2a0bb4f4aef277baf4c0dff", null ],
    [ "map_probe_name", "namespaceSimulation.html#ad84b3a18b90cd099d733648503210f67", null ]
];