var namespaceSimulation =
[
    [ "Feed", "namespaceSimulation_1_1Feed.html", "namespaceSimulation_1_1Feed" ],
    [ "KernelInline", "namespaceSimulation_1_1KernelInline.html", "namespaceSimulation_1_1KernelInline" ],
    [ "MassTransfer", "namespaceSimulation_1_1MassTransfer.html", "namespaceSimulation_1_1MassTransfer" ],
    [ "Dimensions", "structSimulation_1_1Dimensions.html", "structSimulation_1_1Dimensions" ],
    [ "EnvironementProperties", "structSimulation_1_1EnvironementProperties.html", "structSimulation_1_1EnvironementProperties" ],
    [ "Mixture", "classSimulation_1_1Mixture.html", "classSimulation_1_1Mixture" ],
    [ "Phase", "structSimulation_1_1Phase.html", "structSimulation_1_1Phase" ],
    [ "Probes", "classSimulation_1_1Probes.html", "classSimulation_1_1Probes" ],
    [ "ScalarInitializer", "structSimulation_1_1ScalarInitializer.html", "structSimulation_1_1ScalarInitializer" ],
    [ "ScalarSimulation", "classSimulation_1_1ScalarSimulation.html", "classSimulation_1_1ScalarSimulation" ],
    [ "SimulationException", "classSimulation_1_1SimulationException.html", "classSimulation_1_1SimulationException" ],
    [ "SimulationUnit", "classSimulation_1_1SimulationUnit.html", "classSimulation_1_1SimulationUnit" ],
    [ "Specie", "structSimulation_1_1Specie.html", "structSimulation_1_1Specie" ],
    [ "CumulativeProbabilityView", "namespaceSimulation.html#aece6cb625e9b11e5a3d119cd284c46a4", null ],
    [ "DiagonalView", "namespaceSimulation.html#ab9097fcbded128055ffdcc1319213efe", null ],
    [ "init_scalar_f_t", "namespaceSimulation.html#a2ca763e4b1920d29242ce99ed46264d1", null ],
    [ "LeavingFlowIndexType", "namespaceSimulation.html#a567dd61d46269b60e3b26a59c5c58675", null ],
    [ "LeavingFlowType", "namespaceSimulation.html#ace226eabd36088b491c3ba8a93b7d7b3", null ],
    [ "ProbeAutogeneratedBuffer", "namespaceSimulation.html#a7e205e1192f8faf89b55c1d6525413f8", null ],
    [ "SpecieTable", "namespaceSimulation.html#a8a8043f8951284c90553aeb242416f4e", null ],
    [ "ErrorCodes", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bd", [
      [ "BadConcentrationInitLiq", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdaab8d58e72483a0ad6bc6d000993cb04a", null ],
      [ "BadConcentrationInitGas", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdabaf5b84ca77154d5e3258d24429ec242", null ],
      [ "BadInitialiser", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bdaea76fb02103cf3ff94efa52436f0d809", null ],
      [ "MismatchSize", "namespaceSimulation.html#afaa7a23513f9da60616c09d2e09717bda2dc1045efdb911eef2fc5132ae1020c1", null ]
    ] ],
    [ "ScalarInitialiserType", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aa", [
      [ "Uniform", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaaf19516d11f2946f894070e92fcb56b6d", null ],
      [ "Local", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa509820290d57f333403f490dde7316f4", null ],
      [ "File", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa0b27918290ff5323bea1e3b78a9cf04e", null ],
      [ "CustomScript", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa3e7683f51af33ba15b5abc5b1907621f", null ],
      [ "FullCase", "namespaceSimulation.html#afd80d46a94927c6389992f31509571aaa56b419b259c49fa979598027da1f6062", null ]
    ] ],
    [ "makeScalarSimulation", "namespaceSimulation.html#ae5bb8948e2a0bb4f4aef277baf4c0dff", null ]
];