#!/bin/bash

export LD_LIBRARY_PATH=$(pwd)/builddir/laptop/subprojects/cmtool/cmtool/common:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$(pwd)/builddir/laptop/subprojects/cmtool/cmtool/common:$(pwd)/builddir/laptop/subprojects/cmtool/cmtool/cma_read:$LD_LIBRARY_PATH
sudo ldconfig 