#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Author: CASALE Benjamin
# Date: 11/17/2025
# Description: Script to build out-of-project udf file
# -----------------------------------------------------------------------------


# ---------------------------
# Build Configuration
# ---------------------------
# Compiler and linker
CXX="clang++-18"
#TARGET="fdist"
TARGET="fdist"
BUILD_DIR="./builddir/host"

SRC_BD=$1
SRC="$SRC_BD/$TARGET.cpp"
OUT="$BUILD_DIR/libudf_model_$TARGET.so"





DEBUG_FLAGS=" -g O2 -DDEBUG -DENABLE_KOKKOS_PROFILING"
RELEASE_FLAGS=" -O3 -DNDEBUG "

# Compilation flags
COMPILE_FLAGS="
-fdiagnostics-color=always
-D_GLIBCXX_ASSERTIONS=1
-D_FILE_OFFSET_BITS=64
-Wall
-Winvalid-pch
-Wextra
-Wpedantic
-std=c++20
-DUSE_UDF
-DUSE_HIGHFIVE
-fno-math-errno
-march=native
-mtune=native
-DDECLARE_EXPORT_UDF=1"

COMPILE_FLAGS=$COMPILE_FLAGS+$RELEASE_FLAGS

kokkosfolder="kokkos-5.0.0"

# Kokkos include directories
INCLUDE_KOKKOS="-I./$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/core/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/containers/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/algorithms/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/simd/src
-Isubprojects/$kokkosfolder/core/src
-Isubprojects/$kokkosfolder/tpls/desul/include
-Isubprojects/$kokkosfolder/tpls/mdspan/include
-Isubprojects/$kokkosfolder/containers/src
-Isubprojects/$kokkosfolder/algorithms/src
-Isubprojects/$kokkosfolder/simd/src
-Isubprojects/$kokkosfolder
-Isubprojects/kokkos_sampling/public
-Isubprojects/dynlib/public
-isystem subprojects/$kokkosfolder/tpls/mdspan/include
-isystem subprojects/$kokkosfolder/tpls/desul/include"

# Include directories
INCLUDE_DIRS="-Iapps/udf_model
-Iapps/libs/models/public
-Iapps/libs/models/ext
-Iapps/libs/mc/public
-Iapps/libs/common/public
-I$BUILD_DIR/apps/autogenerated"

COMMON_INCLUDE="-I/usr/include"

# Linker flags
# LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined
# -shared
# -fPIC -Wl,-soname,libudf_model_tracker.so -Wl,--start-group $BUILD_DIR/apps/libs/mc/libbiocma_mcst_mc.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkoscore.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkossimd.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkoscontainers.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkosalgorithms.a
# -flto
# -pthread
# -fopenmp
# -fvisibility=hidden
# /usr/lib/x86_64-linux-gnu/libhwloc.so
# /usr/lib/llvm-18/lib/libomp.so
# /lib/x86_64-linux-gnu/libpthread.a -ldl -Wl,--end-group"

#-fvisibility=hidden
LINKER_FLAGS="-rdynamic -Wl,--as-needed -Wl,--no-undefined
-shared
-flto
-fPIC -Wl,-soname,libudf_model_tracker.so -Wl,--start-group

$BUILD_DIR/subprojects/$kokkosfolder/libkokkoscore.a
-pthread
-fopenmp
/usr/lib/x86_64-linux-gnu/libhwloc.so
-ldl -Wl,--end-group"


LINKER_FLAGS2="
-flto 
-pthread
-fopenmp"



# ---------------------------
# Build Process
# ---------------------------

echo "Starting build for $TARGET..."

# Make sure the build directory exists
mkdir -p "$BUILD_DIR"

# Compile and link the project
$CXX -o "$OUT" "$SRC" $LINKER_FLAGS $COMMON_INCLUDE $INCLUDE_DIRS $COMPILE_FLAGS $INCLUDE_KOKKOS --verbose
# g++ -S  -c -o "/tmp/ams.S" -fverbose-asm   "$SRC"  $LINKER_FLAGS $INCLUDE_KOKKOS $COMPILE_FLAGS $INCLUDE_DIRS

if [ $? -eq 0 ]; then
    echo "Build completed successfully!"
else
    echo "Build failed!"
    exit 1
fi
