#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Author: CASALE Benjamin
# Date: 11/17/2025
# Description: Script to build out-of-project udf file
# -----------------------------------------------------------------------------


# ---------------------------
# Build Configuration
# ---------------------------
# Compiler and linker
CXX="clang++-18"
TARGET=$1
BUILD_DIR="./builddir/host"

SRC_BD=$2
SRC="$SRC_BD/$TARGET.cpp"
OUT="$BUILD_DIR/libudf_model_$TARGET.so"





DEBUG_FLAGS=" -g -O1 -DDEBUG -DENABLE_KOKKOS_PROFILING"
RELEASE_FLAGS=" -O3 -DNDEBUG "

# Compilation flags
COMPILE_FLAGS="
-fdiagnostics-color=always
-D_GLIBCXX_ASSERTIONS=1
-D_FILE_OFFSET_BITS=64
-Wall
-Winvalid-pch
-Wextra
-Wpedantic
-std=c++20
-DUSE_UDF
-DUSE_HIGHFIVE
-fno-math-errno
-march=native
-mtune=native
-DDECLARE_EXPORT_UDF=1"

COMPILE_FLAGS=$COMPILE_FLAGS+$RELEASE_FLAGS
# COMPILE_FLAGS=$COMPILE_FLAGS+$DEBUG_FLAGS

kokkosfolder="kokkos-5.0.0"



# Kokkos include directories
INCLUDE_KOKKOS="-I./$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/core/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/containers/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/algorithms/src
-I$BUILD_DIR/subprojects/$kokkosfolder/__CMake_build/simd/src
-Isubprojects/$kokkosfolder/core/src
-Isubprojects/$kokkosfolder/tpls/desul/include
-Isubprojects/$kokkosfolder/tpls/mdspan/include
-Isubprojects/$kokkosfolder/containers/src
-Isubprojects/$kokkosfolder/algorithms/src
-Isubprojects/$kokkosfolder/simd/src
-Isubprojects/$kokkosfolder
-Isubprojects/kokkos_sampling/public
-Isubprojects/dynlib/public
-isystem subprojects/$kokkosfolder/tpls/mdspan/include
-isystem subprojects/$kokkosfolder/tpls/desul/include"

# Include directories
INCLUDE_DIRS="-Iapps/udf_model
-Iapps/libs/models/public
-Iapps/libs/models/ext
-Iapps/libs/mc/public
-Iapps/libs/common/public
-I$BUILD_DIR/apps/autogenerated"

COMMON_INCLUDE="-I/usr/include"


# Linker flags
# LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined
# -shared
# -fPIC -Wl,-soname,libudf_model_tracker.so -Wl,--start-group $BUILD_DIR/apps/libs/mc/libbiocma_mcst_mc.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkoscore.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkossimd.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkoscontainers.a
# $BUILD_DIR/subprojects/$kokkosfolder/libkokkosalgorithms.a
# -flto
# -pthread
# -fopenmp
# -fvisibility=hidden
# /usr/lib/x86_64-linux-gnu/libhwloc.so
# /usr/lib/llvm-18/lib/libomp.so
# /lib/x86_64-linux-gnu/libpthread.a -ldl -Wl,--end-group"
# -fvisibility=hidden


LINKER_FLAGS="-rdynamic -Wl,--as-needed -Wl,--no-undefined
-shared
-flto
-fPIC -Wl,-soname,libudf_model_tracker.so -Wl,--start-group
$BUILD_DIR/subprojects/$kokkosfolder/libkokkoscore.a
-pthread
-fopenmp
/usr/lib/x86_64-linux-gnu/libhwloc.so
-ldl -Wl,--end-group"





LINKER_FLAGS2="
-flto 
-pthread
-fopenmp"



# ---------------------------
# Build Process
# ---------------------------

echo "Starting build for $TARGET..."

# Make sure the build directory exists
mkdir -p "$BUILD_DIR"

# Compile and link the project
$CXX -o "$OUT" "$SRC" $LINKER_FLAGS $COMMON_INCLUDE $INCLUDE_DIRS $COMPILE_FLAGS $INCLUDE_KOKKOS 
# g++ -S  -c -o "/tmp/ams.S" -fverbose-asm   "$SRC"  $LINKER_FLAGS $INCLUDE_KOKKOS $COMPILE_FLAGS $INCLUDE_DIRS



if [ $? -eq 0 ]; then
    echo "Build completed successfully!"
else
    echo "Build failed!"
    exit 1
fi


#  ARGS = -Iapps/udf_model/libudf_model_minimal.so.p 
#  -Iapps/udf_model -I../../apps/udf_model -I../../apps/libs/models/public 
#  -I../../apps/libs/models/ext -I../../apps/libs/mc/public -I../../apps/libs/common/public -Iapps/autogenerated 
#  -I../../apps/autogenerated -Isubprojects/kokkos-5.0.0/__CMake_build 
#  -I../../subprojects/kokkos-5.0.0/__CMake_build -Isubprojects/kokkos-5.0.0/__CMake_build/core/src
#   -I../../subprojects/kokkos-5.0.0/__CMake_build/core/src -I../../subprojects/kokkos-5.0.0/core/src 
#   -I../../subprojects/kokkos-5.0.0/tpls/desul/include -I../../subprojects/kokkos-5.0.0/tpls/mdspan/include 
#   -Isubprojects/kokkos-5.0.0/__CMake_build/containers/src -I../../subprojects/kokkos-5.0.0/__CMake_build/containers/src 
#   -I../../subprojects/kokkos-5.0.0/containers/src -Isubprojects/kokkos-5.0.0/__CMake_build/algorithms/src 
#   -I../../subprojects/kokkos-5.0.0/__CMake_build/algorithms/src -I../../subprojects/kokkos-5.0.0/algorithms/src 
#   -Isubprojects/kokkos-5.0.0/__CMake_build/simd/src -I../../subprojects/kokkos-5.0.0/__CMake_build/simd/src 
#   -I../../subprojects/kokkos-5.0.0/simd/src -I/usr/include -Isubprojects/kokkos-5.0.0 -I../../subprojects/kokkos-5.0.0
#    -I../../subprojects/kokkos_sampling/public -I../../subprojects/dynlib/public 
# -fvisibility=hidden -fdiagnostics-color=always 
#    -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -O2 -g 
#    -DUSE_UDF -DUSE_HIGHFIVE -DUSE_CEAREAL -march=native -mtune=native -DENABLE_KOKKOS_PROFILING 
#    -DEIGEN_NO_CUDA=1 -DDEBUG -DKOKKOS_ENABLE_DEBUG -fPIC -pthread 
#    -fopenmp -isystem../../subprojects/kokkos-5.0.0/tpls/mdspan/include 
#    -isystem../../subprojects/kokkos-5.0.0/tpls/desul/include -DDECLARE_EXPORT_UDF


#  LINK_ARGS = -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,libudf_model_minimal.so 
#  -Wl,--start-group apps/libs/mc/libbiocma_mcst_mc.a apps/libs/common/libbiocma_mcst_common.a 
#  subprojects/kokkos-5.0.0/libkokkoscore.a subprojects/kokkos-5.0.0/libkokkossimd.a subprojects/kokkos-5.0.0/libkokkoscontainers.a 
#  subprojects/kokkos-5.0.0/libkokkosalgorithms.a -flto -flto -ldl /usr/lib/x86_64-linux-gnu/libhwloc.so 
#  /usr/lib/llvm-18/lib/libomp.so /lib/x86_64-linux-gnu/libpthread.a -Wl,--end-group -fopenmp -pthread -flto -fopenmp -fopenmp
