#include <Kokkos_Core.hpp>
#include <cassert>
#include <common/common.hpp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <optional>
#include <scalar_simulation.hpp>
#include <simulation/feed_descriptor.hpp>
#include <simulation/mass_transfer.hpp>
#include <simulation/probe.hpp>
#include <simulation/scalar_initializer.hpp>
#include <simulation/simulation.hpp>
#include <simulation/simulation_exception.hpp>
#include <simulation/simulation_getter.hpp>
#include <stdexcept>

namespace Simulation
{

  Getter::Getter(SimulationUnit const* a) : a_(a)
  {
    if (a_ == nullptr)
    {
      throw std::runtime_error("Simulation ptr is null");
    }
  }

  Getter::Getter(const Getter& m) : Getter(m.a_)
  {
  }

  Getter::~Getter()
  {
    // Dont delete a
  }

  // Simple getter
  bool
  Getter::two_phase_flow() const noexcept
  {
    ;
    assert(a_ != nullptr);
    return a_->is_two_phase_flow;
  }

  [[nodiscard]] double
  Getter::start_time() const noexcept
  {
    assert(a_ != nullptr);
    return a_->starting_time;
  }

  [[nodiscard]] double
  Getter::endtime() const noexcept
  {
    assert(a_ != nullptr);
    return a_->end_time;
  }

  [[nodiscard]] Dimensions
  Getter::getDimensions() const noexcept
  {
    assert(a_ != nullptr);
    return a_->dims;
  }

  const std::unique_ptr<MC::MonteCarloUnit>&
  Getter::mc_unit() const noexcept
  {
    assert(a_ != nullptr);
    return a_->mc_unit;
  }

  const Simulation::Feed::SimulationFeed&
  Getter::get_feed() const noexcept
  {
    assert(a_ != nullptr);
    return a_->feed;
  }

  // Wrapper getter

  std::span<const double>
  Getter::getCliqData() const
  {
    assert(a_ != nullptr);
    return a_->liquid_scalar->getConcentrationData();
  }

  [[nodiscard]] std::span<double>
  Getter::getCliqData_mut() const
  {
    assert(a_ != nullptr);
    return a_->liquid_scalar->getConcentrationData();
  }

  [[nodiscard]] std::optional<std::span<const double>>
  Getter::getCgasData() const
  {
    assert(a_ != nullptr);
    if (!a_->gas_scalar)
    {
      return std::nullopt;
    }
    return a_->gas_scalar->getConcentrationData();
  }

  std::span<const double>
  Getter::getContributionData() const
  {
    assert(a_ != nullptr);
    return a_->liquid_scalar->contribution_span();
  }

  [[nodiscard]] std::optional<std::span<const double>>
  Getter::getMTRData() const
  {
    assert(a_ != nullptr);
    return a_->mt_model.mtr_data();
  }

  std::span<double>
  Getter::getContributionData_mut() const
  {
    assert(a_ != nullptr);
    return a_->liquid_scalar->contribution_span_mut();
  }

  std::ranges::subrange<ProbeIterator, ProbeIterator>
  Getter::it_probes() const
  {
    assert(a_ != nullptr);
    return std::ranges::subrange(a_->probes.cbegin(), a_->probes.cend());
  }

} // namespace Simulation

namespace Simulation
{
  /**SIMULATION IMPL */

  Getter
  SimulationUnit::getter() const noexcept
  {
    return accesor;
  }

  void
  SimulationUnit::setLogger(std::shared_ptr<IO::Logger> _logger)
  {
    logger = std::move(_logger);
  }

  void
  SimulationUnit::setMtrModel(MassTransfer::Type::MtrTypeVariant&& variant)
  {
    if (is_two_phase_flow)
    {
      this->mt_model = Simulation::MassTransfer::MassTransferModel(
          std::move(variant), liquid_scalar, gas_scalar);
    }
  }

  void
  SimulationUnit::setProbes(ProbeType type, ProbeAutogeneratedBuffer&& _probes)
  {
    probes[type] = std::move(_probes);
  }

  // void
  // SimulationUnit::set_kernel_contribs_to_host()
  // {
  //   this->liquid_scalar->set_kernel_contribs_to_host();
  // }

  [[nodiscard]] MC::KernelConcentrationType
  SimulationUnit::getkernel_concentration() const
  {
    return this->liquid_scalar->get_device_concentration();
  }

  void
  SimulationUnit::setEndTime(double _end_time) noexcept
  {
    this->end_time = _end_time;
  }

  void
  SimulationUnit::overwriteStartTime(double _start_time) noexcept
  {
    this->starting_time = _start_time;
  }

  MC::kernelContribution
  SimulationUnit::get_kernel_contribution() const
  {
    return this->liquid_scalar->get_kernel_contribution();
  }

  KernelInline::DispatchOptions
  read_options() noexcept
  {
    const auto p_p_t_contribs = Common::read_env_or(
        "BIOMC_PARTICLES_PER_TEAM_CONTRIBS",
        AutoGenerated::Kernels::particle_per_team_contributions);

    const auto p_p_t_cycle
        = Common::read_env_or("BIOMC_PARTICLES_PER_TEAM_CYCLE",
                              AutoGenerated::Kernels::particle_per_team_cycle);

    const auto p_p_t_move
        = Common::read_env_or("BIOMC_PARTICLES_PER_TEAM_MOVE", 1024UL);

    return { .f_multi_compartment = false,
             .m_p_p_team_model = p_p_t_cycle,
             .m_p_p_team_contribs = p_p_t_contribs,

             .m_p_p_team_move = p_p_t_move,
             .m_p_p_team_leave = 0 };
  }

} // namespace Simulation
