#include <Kokkos_Core.hpp>
#include <common/common.hpp>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
// #include <hydro/impl_mass_transfer.hpp>
// #include <mc/domain.hpp>
// #include <mc/events.hpp>
// #include <mc/prng/prng.hpp>
// #include <mc/unit.hpp>
#include <memory>
#include <optional>
#include <scalar_simulation.hpp>
#include <simulation/feed_descriptor.hpp>
#include <simulation/mass_transfer.hpp>
#include <simulation/probe.hpp>
#include <simulation/scalar_initializer.hpp>
#include <simulation/simulation.hpp>
#include <simulation/simulation_exception.hpp>
// #include <utility>
#ifndef NDEBUG
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#  pragma GCC diagnostic ignored "-Wnan-infinity-disabled"
#endif
// #include <Eigen/Core>
#include <Eigen/Dense>
// #include <Eigen/Sparse>
// #include <eigen_kokkos.hpp>
#ifndef NDEBUG
#  pragma GCC diagnostic pop
#endif

#include <simulation/simulation_getter.hpp>

namespace Simulation
{

  Getter
  SimulationUnit::getter() const
  {
    return accesor;
  }

  Getter::Getter(SimulationUnit* a) : a_(a)
  {
  }

  // Getter::Getter(const std::unique_ptr<SimulationUnit>& a) : Getter(a.get())
  // {
  // }

  Getter::Getter(const Getter& m) : Getter(m.a_)
  {
  }

  Getter::~Getter()
  {
    // Dont delete a
  }

  // std::size_t SimulationUnit::dead_counter() const
  // {
  //   return std::visit([](const auto& container)
  //                     { return container.get_inactive(); },
  //                     mc_unit->container);
  // }

  bool
  Getter::two_phase_flow() const noexcept
  {
    return a_->is_two_phase_flow;
  }

  [[nodiscard]] double&
  Getter::get_start_time_mut() const noexcept
  {
    return a_->starting_time;
  }

  [[nodiscard]] double&
  Getter::get_end_time_mut() noexcept
  {
    return a_->end_time;
  }

  [[nodiscard]] Dimensions
  Getter::getDimensions() const noexcept
  {
    return a_->dims;
  }

  std::span<double>
  Getter::getCliqData() const
  {
    return a_->liquid_scalar->getConcentrationData();
  }

  [[nodiscard]] std::optional<std::span<const double>>
  Getter::getCgasData() const
  {
    if (!a_->gas_scalar)
    {
      return std::nullopt;
    }
    return a_->gas_scalar->getConcentrationData();
  }

  std::span<const double>
  Getter::getContributionData() const
  {
    return a_->liquid_scalar->contribution_span();
  }

  [[nodiscard]] std::optional<std::span<const double>>
  Getter::getMTRData() const
  {
    return a_->mt_model.mtr_data();
  }

  std::span<double>
  Getter::getContributionData_mut() const
  {
    return a_->liquid_scalar->contribution_span_mut();
  }

  const Simulation::Feed::SimulationFeed&
  Getter::get_feed() const
  {
    return a_->feed;
  }

  std::ranges::subrange<ProbeIterator, ProbeIterator>
  Getter::it_probes() const
  {
    return std::ranges::subrange(a_->probes.cbegin(), a_->probes.cend());
  }

  const std::unique_ptr<MC::MonteCarloUnit>&
  Getter::mc_unit() const
  {
    return a_->mc_unit;
  }

  void
  SimulationUnit::setLogger(std::shared_ptr<IO::Logger> _logger)
  {
    logger = std::move(_logger);
  }

  void
  SimulationUnit::setMtrModel(MassTransfer::Type::MtrTypeVariant&& variant)
  {
    if (is_two_phase_flow)
    {
      this->mt_model = Simulation::MassTransfer::MassTransferModel(
          std::move(variant), liquid_scalar, gas_scalar);
    }
  }

  void
  SimulationUnit::setProbes(ProbeType type, ProbeAutogeneratedBuffer&& _probes)
  {
    probes[type] = std::move(_probes);
  }

  void
  SimulationUnit::set_kernel_contribs_to_host()
  {
    this->liquid_scalar->set_kernel_contribs_to_host();
  }

  [[nodiscard]] MC::KernelConcentrationType
  SimulationUnit::getkernel_concentration() const
  {
    return this->liquid_scalar->get_device_concentration();
  }

  kernelContribution
  SimulationUnit::get_kernel_contribution() const
  {
    return this->liquid_scalar->get_kernel_contribution();
  }

  // ProbeAutogeneratedBuffer&
  // SimulationUnit::get_probes(ProbeType type)
  // {
  //   return probes[type];
  // }

  // const CmaUtils::IterationState& SimulationUnit::getState() const
  // {
  //   return state;
  // }

} // namespace Simulation
