#include <biocma_cst_config.hpp>
#include <cstdint>
#include <mc/prng/prng.hpp>

#include <random>

namespace MC
{
  // NOLINTBEGIN
  //
  //[reference source code](http://xoshiro.di.unimi.it/splitmix64.c)
  uint64_t
  next_splitmix64(uint64_t& x) noexcept
  {
    uint64_t z = (x += 0x9e3779b97f4a7c15);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9;
    z = (z ^ (z >> 27)) * 0x94d049bb133111eb;
    return z ^ (z >> 31);
  }
  // NOLINTEND
  //
  uint64_t
  master_seed()
  {
    return std::random_device{}();
  }

  pool_type
  get_pool(std::size_t seed)
  {

#ifdef FIX_SEED
    seed = AutoGenerated::MC::debug_MC_RAND_DEFAULT_SEED;
#else
    seed = std::random_device{}();
#endif

    return (seed);
  }

  KPRNG::KPRNG(size_t _seed) : seed(_seed)
  {
    random_pool = get_pool(this->seed);
  };

  Kokkos::View<double*, ComputeSpace>
  KPRNG::double_uniform(size_t n_sample, double a, double b) const
  {
    Kokkos::View<double*, ComputeSpace> view("sample", n_sample);
    auto local_pool = random_pool;
    Kokkos::parallel_for(
        "fill_sampl", n_sample, KOKKOS_LAMBDA(int&& i) {
          auto generator = local_pool.get_state();
          view(i) = generator.drand(a, b);
          local_pool.free_state(generator);
        });
    Kokkos::fence();

    return view;
  }
} // namespace MC
