#include "common/kokkos_vector.hpp"
#include <mc/prng/prng.hpp>
#include <biocma_cst_config.hpp>
#ifdef NDEBUG
#  include <random>
#endif

namespace MC
{
  KPRNG::KPRNG(size_t _seed)
  {
    if (_seed == 0)
    {
#ifndef NDEBUG
      const size_t seed = AutoGenerated::debug_MC_RAND_DEFAULT_SEED;
#else
      const size_t seed = std::random_device{}();
#endif
      random_pool = Kokkos::Random_XorShift64_Pool<>(seed);
    }
    else
    {
      random_pool = Kokkos::Random_XorShift64_Pool<>(_seed);
    }
  };

  Kokkos::View<double *, ComputeSpace>
  KPRNG::double_uniform(size_t n_sample, double a, double b) const
  {
    Kokkos::View<double *, ComputeSpace> view("sample", n_sample);
    auto local_pool = random_pool;
    Kokkos::parallel_for("fill_sampl",
        n_sample, KOKKOS_LAMBDA(int &&i) {
          auto generator = local_pool.get_state();
          view(i) = generator.drand(a, b);
          local_pool.free_state(generator);
        });
    Kokkos::fence();

    return view;
  }
} // namespace MC