#ifndef __MC_UNIT_HPP__
#define __MC_UNIT_HPP__

#include <mc/domain.hpp>
#include <mc/events.hpp>
#include <mc/particles_container.hpp>
#include <mc/prng/prng.hpp>
#include <mc/traits.hpp>
#include <variant>
#include <variant_model.hpp>

/**
 * @namespace MC
 * @brief Namespace that contains classes and structures related to Monte Carlo
 * (MC) simulations.
 *
 * This namespace encapsulates all the components used in Monte Carlo
 * simulations, including data structures for managing simulation state and
 * results.
 */
namespace MC
{
  RuntimeParameters load_tuning_constant();

  /**
   * @brief General-purpose Monte Carlo unit to carry out simulations.
   *
   * The MonteCarloUnit struct encapsulates the components necessary for
   * running Monte Carlo simulations.
   * The MonteCarloUnit is non-copyable but movable, ensuring that only one
   * instance manages its resources at any time.
   */
  struct MonteCarloUnit
  {
    /// Container to manage and store simulation events
    EventContainer events;
    /// Domain in which the simulation is performed
    ReactorDomain domain;

    AutoGenerated::ContainerVariant container;
    /// Random number generator used for Monte Carlo methods
    MC::KPRNG rng;
    /// Initial weight or factor used in the simulation
    double init_weight{};

    // Non-copyable, movable
    MonteCarloUnit(const MonteCarloUnit&) = delete;
    MonteCarloUnit& operator=(const MonteCarloUnit&) = delete;
    MonteCarloUnit(MonteCarloUnit&&) noexcept = default;
    MonteCarloUnit& operator=(MonteCarloUnit&&) noexcept = default;
    MonteCarloUnit() = default;
    ~MonteCarloUnit() = default;

    [[nodiscard]] uint64_t n_particle() const;

    [[nodiscard]] std::vector<uint64_t> getRepartition() const;

    [[nodiscard]] std::vector<std::string> getModelList() const;

    template <class Archive>
    void
    serialize(Archive& ar)
    {
      ar(init_weight, events, domain, container);

      std::visit(
          [&ar](auto& _container)
          {
            ar(_container);
            _container.change_runtime(load_tuning_constant());
          },
          container);
    }
  };

} // namespace MC

#endif //__MC_UNIT_HPP__
