#ifndef __CORE__PROBE_HPP__
#define __CORE__PROBE_HPP__

#include "Kokkos_Core_fwd.hpp"
#include <Kokkos_Core.hpp>
#include <biocma_cst_config.hpp>
#include <cstddef>
#include <cstdint>
#include <unordered_map>

namespace Simulation
{

  enum class ProbeType : unsigned
  {
    LeavingTime = 0,
    DivisionTime
  };

  static const std::array<std::string, 2> map_probe_name
      = { "LeavingTime", "DivisionTime" };

  // TODO: keep thi structure as a bulkstorage for fast compute but consider
  // sorting into bins when exporting it to avoid unnecessary amount of data
  //  Unordered map could be adapted

  // TODO: dangerous struct where behaviour is based on active flag
  // Active flag is set on constructor if constexpr flag use_probe is set
  // set check active BUT the other dont, clear/get can crash if active==false
  // then this is caller responsability

  // Clean this api by remove active flag: use full c++20 template/requires
  // style like this : template <typename T = void>
  //   [[nodiscard]] KOKKOS_INLINE_FUNCTION bool set(double val) const
  //      requires(use_probe == true){ usual impl }
  // template <typename T = void>
  //  [[nodiscard]] KOKKOS_INLINE_FUNCTION bool set(double val) const
  //      requires(use_probe == false){ return false (or true whatever) }

  /*
  TODO, it seems that after some calculation (example cstr 0d) size(division
  probes) = number of tally+1 where the last probe is 0 where size(leaving time)
  == tally Is it a bug ?
  */

  /**  @brief Class to store time event as bulk storage  */
  template <std::size_t buffer_size> class Probes
  {
  public:
    template <typename Space>
    using buffer_type
        = Kokkos::View<double[buffer_size], Kokkos::LayoutRight, Space>;

    // WARNING : marked  const but mutates state
    void clear() const;

    [[nodiscard]] KOKKOS_INLINE_FUNCTION bool set(double val) const;

    [[nodiscard]] bool need_export() const noexcept;

    // [[nodiscard]] const double* raw_get() const;

    [[nodiscard]] std::span<const double> get() const;

    Probes();

  private:
    bool active{};
    // NOLINTBEGIN
    buffer_type<Kokkos::DefaultExecutionSpace> buffer;
    Kokkos::View<uint64_t, Kokkos::SharedSpace> internal_counter;
    buffer_type<Kokkos::DefaultHostExecutionSpace> host_buffer;
    // NOLINTEND
  };

  using ProbeAutogeneratedBuffer = Probes<AutoGenerated::probe_buffer_size>;

  using MapProbes = std::unordered_map<ProbeType, ProbeAutogeneratedBuffer>;

  using ProbeIterator = MapProbes::const_iterator;

} // namespace Simulation

namespace Simulation
{
  template <std::size_t buffer_size> Probes<buffer_size>::Probes()
  {
    if (AutoGenerated::FlagCompileTime::use_probe)
    {
      active = true;
      buffer = buffer_type<Kokkos::DefaultExecutionSpace>("probe_buffer");
      internal_counter = Kokkos::View<uint64_t, Kokkos::SharedSpace>("i_c");
      host_buffer
          = buffer_type<Kokkos::DefaultHostExecutionSpace>("host_buffer");
    }
    clear();
  }

  // template <std::size_t buffer_size>
  // KOKKOS_INLINE_FUNCTION bool
  // Probes<buffer_size>::set(double val) const
  // {
  //   const auto i = (active) ? Kokkos::atomic_fetch_inc(&internal_counter()) :
  //   0;

  //   // Innaccessible from host space if use CUDA because of direct assignment
  //   if (active&&(i < buffer_size) )
  //   {
  //     // this->buffer(i) = val;
  //     // if constexpr (is_view_accessible<decltype(buffer),
  //     // Kokkos::DefaultExecutionSpace>())
  //     {
  //       this->buffer(i) = val;
  //     }
  //     // else
  //     // {
  //     //   // Kokkos::deep_copy(buffer(i), val);
  //     //   Kokkos::View<double, Kokkos::DefaultHostExecutionSpace>
  //     //   single_val("SingleValue"); single_val() = val;

  //     //   Kokkos::deep_copy(buffer(i), single_val);
  //     // }
  //     return true;
  //   }
  //   return false;
  // }

  template <std::size_t buffer_size>
  KOKKOS_INLINE_FUNCTION bool
  Probes<buffer_size>::set(double val) const
  {

    //active is VERY LIKELY to be true if we get here then the
    // Calling this function with a non active probe meant that there is
    // something wrong in the caller If not active just do nothing, returns
    // falls

    // const auto i = (active) ? Kokkos::atomic_fetch_inc(&internal_counter()) :
    // 0;

    // TODO Innaccessible from host space if use CUDA because of direct
    // assignment
    //  TODO Use current space are template parameter
    if (active) [[likely]]
    {
      if (const auto i = Kokkos::atomic_fetch_inc(&internal_counter());
          i < buffer_size)
      {
        this->buffer(i) = val;
        return true;
      }
    }

    return false;
  }

  template <std::size_t buffer_size>
  bool
  Probes<buffer_size>::need_export() const noexcept
  {
    return active && (internal_counter() >= buffer_size);
  }

  template <std::size_t buffer_size>
  void
  Probes<buffer_size>::clear() const
  {
    Kokkos::deep_copy(buffer, 0.);
    Kokkos::deep_copy(internal_counter, 0);
  }

  template <std::size_t buffer_size>
  [[nodiscard]] std::span<const double>
  Probes<buffer_size>::get() const
  {
    // TODO this should be alsway internal_counter(), but in case internal
    // counter > buffersize (error in race condition) size never overrun
    // buffer_size
    const auto return_size = std::min(buffer_size, internal_counter());
    assert(return_size <= buffer_size);
    /*
    // Safe: returning a span of size return_size is ok; the span may be smaller
    than the full host_buffer
    */
    Kokkos::deep_copy(host_buffer, buffer);
    return { host_buffer.data(), return_size };
  }
} // namespace Simulation

#endif