#include <Kokkos_Assert.hpp>
#include <biocma_cst_config.hpp>
#include <common/common.hpp>
#include <common/logger.hpp>
#include <dataexporter/data_exporter.hpp>
#include <dataexporter/partial_exporter.hpp>
#include <mc/events.hpp>
#include <optional>
#include <simulation/probe.hpp>
#include <utility>
#include <vector>

namespace Core
{
  PartialExporter::PartialExporter(
      const ExecInfo& info,
      std::string_view _filename,
      std::optional<export_metadata_t> user_description)
      : DataExporter(info, _filename, std::move(user_description))

  {
    write_properties(std::nullopt, metadata);
  }

  void
  PartialExporter::init_fields(uint64_t n_iter, uint64_t n_compartments)
  {
    std::vector<unsigned long long> chunk = { 1, n_compartments };
    const uint64_t n_expected_export = n_iter + 2; // Add first + last
    MultiMatrixDescription particle_repartition
        = { .name = "records/number_particle",
            .dims = { 1, n_compartments },
            .max_dims = { n_expected_export, n_compartments },
            .chunk_dims = chunk,
            .compression = true,
            .is_integer = true };

    chunk = std::vector<unsigned long long>({ 1, MC::number_event_type });

    MultiMatrixDescription tallies
        = { .name = "records/tallies",
            .dims = { 1, MC::number_event_type },
            .max_dims = { n_expected_export, MC::number_event_type },
            .chunk_dims = chunk,
            .compression = true,
            .is_integer = true };
    this->prepare_matrix(particle_repartition);
    this->prepare_matrix(tallies);

    if constexpr (AutoGenerated::FlagCompileTime::use_probe)
    {
      // Warning: with some STL implementation,initialiser list constructor
      // with ONE value (vector({value})) leads to vector of zeros with
      // vector.size = value instead of vector[0]=value.
      //  auto chunk = std::vector<unsigned long long>(1);
      //  chunk[0]=AutoGenerated::probe_buffer_size*sizeof(double);

      // This will only work if all probes have the same buffer_size
      // Until (so far) v1.0.0  it is the case with simulation probes
      std::vector<unsigned long long> chunk
          = { AutoGenerated::probe_buffer_size * sizeof(double) };

      uint64_t counter = 0;
      for (const auto& name : Simulation::map_probe_name)
      {

        const auto ds_name = IO::format("probes/", name);
        probe_counter_n_element.insert({ name, counter });
        counter += 1;
        MultiMatrixDescription probes
            = { .name = ds_name,
                .dims = { 0 },
                .max_dims = { (n_expected_export + 1)
                              * AutoGenerated::probe_buffer_size },
                .chunk_dims = chunk,
                .compression = true,
                .is_integer = false };

        this->prepare_matrix(probes);
      }
    }
  }

  void
  PartialExporter::write_number_particle(
      const std::vector<size_t>& distribution)
  {
    append_matrix("records/number_particle", distribution);

    export_counter++;
  }

  void
  PartialExporter::write_probe(const std::string& probe_name,
                               std::span<const double> data)
  {
    std::string data_set_name = IO::format("probes/", probe_name);

    auto& counter
        = this->probe_counter_n_element.at(probe_name); // Throw if bad name

    append_array(data_set_name, data, counter);
    counter += data.size();
  }

  void
  PartialExporter::write_particle_data(PostProcessing::BonceBuffer&& bonce,
                                       const std::string& ds_name,
                                       bool compress_data)
  {
    PROFILE_SECTION("write_particle_data")
    const auto& [particle_values, spatial_values, ages_values, names] = bonce;

    const size_t n_particles = particle_values.extent(1);
    const size_t n_compartments = bonce.spatial_values.extent(1);

    if (ages_values.has_value())
    {
      auto* ptr_ages = Kokkos::subview(*ages_values, 0, Kokkos::ALL).data();
      this->write_matrix(
          ds_name + "age_hydro/", { ptr_ages, n_particles }, compress_data);
      ptr_ages = Kokkos::subview(*ages_values, 1, Kokkos::ALL).data();
      this->write_matrix(
          ds_name + "age/", { ptr_ages, n_particles }, compress_data);
    }
    KOKKOS_ASSERT(particle_values.extent(0) == bonce.vnames.size());
    // Warning UB  if len(kindex)!=len(vnames)
    for (size_t i_name = 0; i_name < bonce.vnames.size(); ++i_name)
    {
      const auto* ptr_particles
          = Kokkos::subview(particle_values, i_name, Kokkos::ALL).data();

      const auto* ptr_spatial
          = Kokkos::subview(spatial_values, i_name, Kokkos::ALL).data();

      this->write_matrix(ds_name + names[i_name],
                         { ptr_particles, n_particles },
                         compress_data);
      this->write_matrix(ds_name + "spatial/" + names[i_name],
                         { ptr_spatial, n_compartments },
                         false);
    }
  }
  void
  PartialExporter::write_tally(std::span<const std::size_t> data)
  {
    append_matrix("records/tallies", data);
  }

}; // namespace Core
