#ifndef __EXEC_INFO_HPP__
#define __EXEC_INFO_HPP__

#include <biocma_cst_config.hpp>
#include <common/has_serialize.hpp>
#include <cstddef>
#include <cstdint>
#include <string>

// clang-format off
struct KernelDispatchOptions
{
  std::size_t m_p_p_team_model    = AutoGenerated::Kernels::particle_per_team_cycle;
  std::size_t m_p_p_team_contribs = AutoGenerated::Kernels::particle_per_team_contributions;
  std::size_t m_p_p_team_move     = AutoGenerated::Kernels::particle_per_team_move;
  std::size_t m_p_p_team_leave    = AutoGenerated::Kernels::particle_per_team_leave;
};
// clang-format on

struct ExecInfo
{
  uint64_t run_id;
  uint32_t n_rank;
  uint32_t current_rank;
  uint32_t thread_per_process;
  bool verbose;
  KernelDispatchOptions kernel_options;

  template <class Archive, typename T = void>
  std::enable_if_t<AutoGenerated::FlagCompileTime::use_cereal_serde, T>
  serialize(Archive& ar)
  {
    // Do not save kernel_options because options can change accross run and
    // also overwritten before run
    ar(n_rank, current_rank, thread_per_process, verbose, run_id);
  }

  static std::string get_version();
};

inline std::ostream&
operator<<(std::ostream& stream, const ExecInfo& obj)
{
  stream << obj.run_id << "\t" << obj.n_rank << "\t" << obj.thread_per_process
         << "\t";
  return stream;
}

#endif //__EXEC_INFO_HPP__
