#include <Kokkos_Core.hpp>
#include <api/api.hpp>
#include <api/results.hpp>
#include <biocma_cst_config.hpp>
#include <common/common.hpp>
#include <common/execinfo.hpp>
#include <common/logger.hpp>
#include <common/traits.hpp>
#include <core/case_data.hpp>
#include <core/global_initaliser.hpp>
#include <core/simulation_parameters.hpp>
#include <cstddef>
#include <exception>
#include <filesystem>
#include <memory>
#include <new>
#include <optional>
#include <simulation/feed_descriptor.hpp>
#include <simulation/mass_transfer.hpp>
#include <simulation/simulation.hpp>
#include <string>
#include <udf_handle.hpp>
#include <utility>
#include <vector>
#include <wrap_init_model_selector.hpp>
#ifndef NO_MPI
#  include <mpi_w/wrap_mpi.hpp>
#endif
constexpr int ID_VERIF = 2025;

#define CHECK_OR_RETURN(cond, msg)                                             \
  if ((cond))                                                                  \
  {                                                                            \
    return ApiResult(msg);                                                     \
  }

namespace
{
  static std::shared_ptr<DynamicLibrary> udf_handle = nullptr;

  // Simple helper
  // TODO: specialized for floatpoin type and integer
  template <typename T>
  bool
  is_strict_positive(const T& a)
  {
    return a > T(0);
  }

  template <typename T>
  bool
  is_positive(const T& a)
  {
    return a >= T(0);
  }

  ApiResult
  check_required(const Core::UserControlParameters& params, bool to_load)
  {

    if (!is_strict_positive(params.final_time))
    {
      return ApiResult("Final time must be positive");
    }

    if (!is_positive(params.delta_time))
    {
      return ApiResult("Delta time must be positive");
    }
    if (params.cma_case_path.empty())
    {
      return ApiResult("CM path is empty");
    }

    if ((!params.serde_file.has_value() && params.load_serde)
        || (!params.load_serde && params.serde_file.has_value()))
    {
      return ApiResult("If serde, needs file path");
    }

    if (!to_load)
    {
      if (!is_strict_positive(params.biomass_initial_concentration))
      {
        return ApiResult(
            "biomass_initial_concentration should be strictly positive ");
      }
      if (params.number_particle == 0)
      {
        return ApiResult("Number of particle should be positive");
      }
    }

    return ApiResult(); // Ok !
  }

} // namespace

namespace Api
{

  void
  finalise()
  {

    if constexpr (AutoGenerated::FlagCompileTime::use_mpi)
    {
#ifndef NO_MPI
      // WrapMPI::barrier();
      // WrapMPI::finalize();
#endif
    }
    if (!Kokkos::is_finalized() && Kokkos::is_initialized())
    {
      Kokkos::finalize();
    }
  }

  [[nodiscard]] int
  SimulationInstance::get_id() const
  {
    return id;
  }

  ApiResult
  SimulationInstance::add_feed(Simulation::Feed::FeedDescriptor feed_type,
                               Phase phase)
  {
    if (!feed.has_value())
    {
      feed = Simulation::Feed::SimulationFeed{ std::nullopt, std::nullopt };
    }

    this->feed->add_feed(move_allow_trivial(feed_type), phase);

    return ApiResult(); // TODO FIX ERROR
  }

  // ApiResult
  // SimulationInstance::set_feed_constant(double _flow,
  //                                       double _concentration,
  //                                       std::size_t _species,
  //                                       std::size_t _position,

  //                                       bool gas,
  //                                       bool fed_batch)
  // {
  //   auto phase = gas ? Phase::Gas : Phase::Liquid;

  //   auto constant_feed = Simulation::Feed::FeedFactory::constant(
  //       _flow, _concentration, _species, _position, std::nullopt,
  //       !fed_batch);
  //   // Negates fed_batch because expect set_output wich is !fed_batch
  //   return set_feed(constant_feed, phase);
  // }

  // ApiResult
  // SimulationInstance::set_feed_constant_different_output(
  //     double _flow,
  //     double _concentration,
  //     std::size_t _species,
  //     std::size_t input_position,
  //     std::size_t output_position,

  //     bool gas)
  // {
  //   auto phase = gas ? Phase::Gas : Phase::Liquid;
  //   auto constant_feed = Simulation::Feed::FeedFactory::constant(
  //       _flow, _concentration, _species, input_position, output_position, true);
  //   return set_feed(constant_feed, phase);
  // }

  SimulationInstance::SimulationInstance(int argc,
                                         char** argv,
                                         std::optional<std::size_t> run_id)
      : id(ID_VERIF), auto_mtr(false)
  {

    // TODO: How to register logger before runtime_init ?
    // Need to log_start_up in API (not in main)
    //  Log message in runtime_init is printed with ostream
    _data.exec_info = Core::runtime_init(argc, argv, run_id);
    std::atexit(Api::finalise);
  }

  SimulationInstance::~SimulationInstance()
  {
    _data = Core::CaseData(); // Explicity delete everything before
    udf_handle.reset();
    // Api::finalise();
  }

  std::optional<std::unique_ptr<SimulationInstance>>
  SimulationInstance::init(int argc,
                           char** argv,
                           std::optional<std::size_t> run_id) noexcept
  {
    PROFILE_SECTION("Initialisation")
    auto ptr = std::unique_ptr<SimulationInstance>(
        new (std::nothrow) SimulationInstance(argc, argv, run_id));
    if (ptr == nullptr)
    {
      return std::nullopt;
    }
    return ptr;
  }

  ApiResult
  SimulationInstance::exec() noexcept
  {

    if (!loaded && (!registered || !applied))
    {
      return ApiResult("Error apply first");
    }

    if (logger)
    {
      logger->print(
          "Simulation",
          IO::format("Running ",
                     std::to_string(this->_data.exec_info.current_rank),
                     "..."));
    }

    try
    {

      Core::exec(logger, std::move(this->_data));
      return ApiResult();
    }
    catch (std::exception& e)
    {
      if (logger)
      {
        logger->alert("EXEC", e.what());
      }
      return ApiResult(e.what());
    }
  }

  ApiResult
  SimulationInstance::apply_load() noexcept
  {
    // Checks
    // CHECK_OR_RETURN(!check_required(this->params, true), "Check params");

    if (auto r = check_required(this->params, true); r.invalid())
    {
      return r;
    }

    CHECK_OR_RETURN(loaded, "Already loaded");

    try
    {
      if (auto opt_case = Core::load(logger,
                                     this->_data.exec_info,
                                     std::move(this->params),
                                     this->feed))
      {
        this->_data = std::move(*opt_case);
        this->loaded = true;
        return ApiResult();
      }
    }
    catch (std::exception& e)
    {
      return ApiResult(e.what());
    }

    return ApiResult("Error loading case");
  }

  ApiResult
  SimulationInstance::set_mtr(
      Simulation::MassTransfer::Type::MtrTypeVariant&& variant)
  {
    //??
    mtr_type = variant;
    auto_mtr = false;
    return ApiResult();
  }

  void
  SimulationInstance::set_auto_mtr()
  {
    auto_mtr = true;
  }

  ApiResult
  SimulationInstance::apply() noexcept
  {

    if (auto r = check_required(this->params, false); r.invalid())
    {
      return r;
    }

    CHECK_OR_RETURN(loaded, "Already loaded");
    CHECK_OR_RETURN(!registered, "Register first");

    Core::GlobalInitialiser global_initializer(_data.exec_info, params, logger);

    {
      auto transitionner = global_initializer.init_transitionner();

      CHECK_OR_RETURN(!transitionner, "Error when apply: transitionner");
      _data.transitioner = std::move(*transitionner);
    }

    CHECK_OR_RETURN(!global_initializer.init_feed(feed),
                    "Error when apply: feed");

    auto __simulation
        = global_initializer.init_simulation(this->scalar_initializer_variant);

    CHECK_OR_RETURN(!__simulation.has_value(), "Error when apply: simulation");

    auto simulation = std::move(*__simulation);

    if (logger)
    {
      simulation->setLogger(logger);
    }

    if (mtr_type)
    {
      global_initializer.init_mtr_model(*simulation, std::move(*mtr_type));
    }
    else if (auto_mtr)
    {

      std::vector<double> kla(simulation->getter().getDimensions().n_species);
      if (kla.size() > 1)
      {
        kla[1] = 0.2; // 700 h-1
      }

      auto auto_mtr_type = Simulation::MassTransfer::Type::FixedKla{ kla };
      global_initializer.init_mtr_model(*simulation, std::move(auto_mtr_type));
      // TODO check if turburlence + fallback to kla
    }

    CHECK_OR_RETURN(!global_initializer.check_init_terminate(),
                    "Error apply: missing one initialization step");

    _data.params = global_initializer.get_parameters();
    _data.simulation = std::move(simulation);

    applied = true;

    return ApiResult();
  }

  ApiResult
  SimulationInstance::register_scalar_initiazer(
      Core::ScalarFactory::ScalarVariant&& var)
  {
    this->scalar_initializer_variant = std::move(var);
    return ApiResult();
  }

  ApiResult
  SimulationInstance::apply(bool to_load) noexcept
  {
    auto opt_udf = Unsafe::load_udf(params.model_name);
    if (opt_udf.valid())
    {
      udf_handle = opt_udf.gets();
    }
    else
    {
      if (logger)
      {
        logger->alert("UDF",
                      "UDF shared library not found, fallback to default");
      }
      params.model_name = "None"; // Fallback
    }
    if (to_load)
    {
      return apply_load();
    }

    return apply();
  }

  ApiResult
  SimulationInstance::register_parameters(
      Core::UserControlParameters&& _params) noexcept
  {
    params = std::move(_params);
    registered = true;
    return ApiResult();
  }

  bool
  SimulationInstance::register_result_path(std::string_view path)
  {
    // TODO Check path
    this->params.results_file_name = path;

    return true; // TODO
  }

  ApiResult
  SimulationInstance::register_initialiser_file_path(std::string_view path)
  {
    this->params.initialiser_path = path;
    return ApiResult(); // TODO
  }

  ApiResult
  SimulationInstance::register_cma_path(std::string_view path)
  {

    std::filesystem::path p(path);

    if (!std::filesystem::exists(p) || !std::filesystem::is_directory(p))
    {
      return ApiResult("Flowmap doesn´t exist or is invalid");
    }

    std::string normalized = p.string();
    if (normalized.back() != std::filesystem::path::preferred_separator)
    {
      normalized += std::filesystem::path::preferred_separator;
    }

    this->params.cma_case_path = normalized;

    return ApiResult();
  }

  ApiResult
  SimulationInstance::register_initial_condition(
      Core::ScalarFactory::ScalarVariant&& type)
  {
    scalar_initializer_variant = std::move(type);
    return ApiResult();
  }

  bool
  SimulationInstance::register_serde(std::string_view path)
  {
    this->params.serde_file = path;
    this->params.load_serde = true;
    return true;
  }

  ApiResult
  SimulationInstance::register_model_name(std::string_view path)
  {
    this->params.model_name = path;
    return ApiResult();
  }

  std::vector<std::string>
  SimulationInstance::get_model_list() noexcept
  {
    return AutoGenerated::get_model_list();
  }

  [[nodiscard]] const ExecInfo&
  SimulationInstance::get_exec_info() const
  {
    return _data.exec_info;
  }

} // namespace Api
