#include <udf_handle.hpp>

#ifdef USE_UDF
#  include <common/env_var.hpp>
#  include <wrap_init_model_selector.hpp>
#endif

namespace Unsafe
{
#ifndef USE_UDF
  struct DynamicLibrary;
  Result<std::shared_ptr<DynamicLibrary>, std::string>
  load_udf(std::string_view model_name)
  {
    (void)path;
    (void)model_name;
    return Result<std::shared_ptr<DynamicLibrary>, std::string>(nullptr);
  };

#else

  Result<std::shared_ptr<DynamicLibrary>, std::string>
  load_udf(std::string_view model_name)
  {
    const bool f_load_udf = AutoGenerated::request_udf(model_name);

    const auto name = Common::read_env<std::string>("BIOMC_LIB_UDF");
    if (f_load_udf)
    {
      if (!name.has_value())
      {
        return Result<std::shared_ptr<DynamicLibrary>, std::string>(
            "var BIOMC_LIB_UDF not found");
      }
      return Result<std::shared_ptr<DynamicLibrary>, std::string>(
          UnsafeUDF::Loader::init_lib(*name));
    }
    return Result<std::shared_ptr<DynamicLibrary>, std::string>();
  }

#endif
} // namespace Unsafe
