#ifndef __MODEL_CONFIG_LOADER__
#define __MODEL_CONFIG_LOADER__

#include <common/execinfo.hpp>
#include <mc/particles_container.hpp>
#include <mc/traits.hpp>
#include <variant_model.hpp>

namespace Models
{

  template <typename Model>

    requires(std::is_constructible_v<AutoGenerated::ContainerVariant,
                                     MC::ParticlesContainer<Model>>
             && ConfigurableModel<Model>)

  Model::Config
  get_model_configuration(const ExecInfo& info, std::size_t n)
  {
    return Model::get_config(info, n);
  }
  template <typename Model>

    requires(std::is_constructible_v<AutoGenerated::ContainerVariant,
                                     MC::ParticlesContainer<Model>>
             && NonConfigurableModel<Model>)

  Model::Config
  get_model_configuration(const ExecInfo& info, std::size_t n)
  {
    (void)n;
    (void)info;
    return std::nullopt;
  }

}; // namespace Models

#endif
