#ifndef __MODEL_CONFIG_LOADER__
#define __MODEL_CONFIG_LOADER__

#include <mc/particles_container.hpp>
#include <mc/traits.hpp>
#include <variant_model.hpp>

namespace Models
{

  template <typename Model>

    requires(std::is_constructible_v<AutoGenerated::ContainerVariant,
                                     MC::ParticlesContainer<Model>>)

  Model::Config get_model_configuration(std::size_t n)
  {
    return Model::get_config(n);
  }

}; // namespace Models

#endif
