#include "simulation/simulation_getter.hpp"
#include <Kokkos_Core.hpp>
#include <biocma_cst_config.hpp>
#include <common/execinfo.hpp>
#include <common/logger.hpp>
#include <core/case_data.hpp>
#include <core/global_initaliser.hpp>
#include <host_specific.hpp>
#include <impl_post_process.hpp>
#include <ios>
#include <memory>
#include <optional>
#include <ostream>
#include <serde.hpp>
#include <simulation/descriptors/dimensions.hpp>
#include <simulation/feed_descriptor.hpp>
#include <simulation/probe.hpp>
#include <simulation/simulation.hpp>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <worker_specific.hpp>

#ifndef NO_MPI
#  include <mpi_w/wrap_mpi.hpp>
#endif

namespace Core
{

  std::string
  exporter_filename(const ExecInfo& exec, const SimulationParameters& params)
  {
    std::stringstream filename;
    filename << params.results_file_name << "_partial_" << exec.current_rank
             << ".h5";
    return filename.str();
  }

  void
  init_partial_exporter(Core::PartialExporter& partial_exporter,
                        const CaseData& case_data)
  {
    auto getter = case_data.simulation->getter();
    const auto [_, n_compartment] = getter.getDimensions();
    partial_exporter.init_fields(case_data.params.number_exported_result,
                                 n_compartment);

    // TODO: so far all probes are active or all probes are inactive
    // Find a way to select them without branching in kernels
    {
      auto probes = Simulation::ProbeAutogeneratedBuffer();
      case_data.simulation->setProbes(Simulation::ProbeType::LeavingTime,
                                      std::move(probes));
    }

    {
      auto probes = Simulation::ProbeAutogeneratedBuffer();
      case_data.simulation->setProbes(Simulation::ProbeType::DivisionTime,
                                      std::move(probes));
    }

    partial_exporter.write_number_particle(getter.mc_unit()->getRepartition());
    PostProcessing::save_particle_state(getter, partial_exporter);
  }

  CaseData::CaseData()
      : simulation(nullptr), params(),
        transitioner(CmaUtils::TransitionnerPtrType::from_raw(nullptr)),
        exec_info()
  {
  }

  void
  exec(std::shared_ptr<IO::Logger> logger, CaseData case_data)
  {
    // TODO Find orphan profile_section : Kokkos::Profiling::popRegion() called
    // outside  of an actve region. Previous regions:

    const auto filename
        = exporter_filename(case_data.exec_info, case_data.params);
    Core::PartialExporter partial_exporter(ExecInfo(), filename);
    init_partial_exporter(partial_exporter, case_data);
    partial_exporter.set_logger(logger);
    auto* const sim = case_data.simulation.get();

    if (case_data.exec_info.current_rank != 0
        && !AutoGenerated::FlagCompileTime::use_mpi)
    {
      throw std::runtime_error("Rank should be 0 without MPI");
    }

    // TODO TRY/CATCH exec and handle error saving state in /tmp
    if (case_data.exec_info.current_rank == 0)
    {
      host_process(logger,
                   case_data.exec_info,
                   *sim,
                   case_data.params,
                   std::move(case_data.transitioner),
                   partial_exporter);
    }
    else
    {
// FIXME (replace ifdef by forward declaration)
#ifndef NO_MPI
      workers_process(logger,
                      case_data.exec_info,
                      *sim,
                      case_data.params,
                      partial_exporter);
#endif
    }

    if constexpr (AutoGenerated::FlagCompileTime::use_probe)
    {
      PostProcessing::save_probes(sim->getter(), partial_exporter, true);
    }
    if (case_data.params.save_final_serde)
    {
      // Load/Save works fine but be careful with big data (can crash due to
      // overflow) mainly on GPU
      if constexpr (AutoGenerated::FlagCompileTime::use_cereal_serde)
      {
        do_serde(case_data);
      }
      else
      {
        logger->alert("CaseData",
                      "Saving final results are requested but no serde "
                      "implementation was given");
      }
    }

    // v1.0.0: Reset is useless lvalue calls RAII
    //  case_data.simulation.reset();
  }

  std::optional<Core::CaseData>
  load(std::shared_ptr<IO::Logger>& logger,
       const ExecInfo& exec,
       const UserControlParameters&& params,
       std::optional<Simulation::Feed::SimulationFeed> feed)
  {
    return impl_load(
        logger, exec, std::forward<decltype(params)>(params), std::move(feed));
  }

  ExecInfo
  runtime_init(int argc, char** argv, std::optional<std::size_t> force_run_id)
  {
    ExecInfo info{};

    int rank = 0;
    int size = 1;
    if constexpr (AutoGenerated::FlagCompileTime::use_mpi)
    {
#ifndef NO_MPI
      if (!WrapMPI::is_initialized())
      {
        // MPI_Init(&argc, &argv);
        MPI_Init(NULL, NULL); // FIXME with python API
      }
      MPI_Comm_rank(MPI_COMM_WORLD, &rank);
      MPI_Comm_size(MPI_COMM_WORLD, &size);

#endif
    }
    if (!Kokkos::is_finalized() && !Kokkos::is_initialized())
    {
      Kokkos::initialize(argc, argv);
    }

#ifndef NO_MPI
    WrapMPI::barrier();
#endif

    if (rank == 0)
    {
      if constexpr (AutoGenerated::FlagCompileTime::verbose)
      {
        std::ostream& out_stream = std::cout;
        std::stringstream os;
        Kokkos::print_configuration(os, true);
        std::string line;
        std::ios_base::sync_with_stdio(false);
        while (std::getline(os, line))
        {
          out_stream << IO::AnsiCode::green
                     << "[Kokkos]: " << IO::AnsiCode::reset << line << '\n';
        }
        if constexpr (AutoGenerated::FlagCompileTime::use_mpi)
        {
          out_stream << IO::AnsiCode::green << "[Host]: " << IO::AnsiCode::reset
                     << "Number of MPI nodes: " << size << '\n';
        }
        std::ios_base::sync_with_stdio(true);
        std::flush(out_stream);
      }
    }

    if constexpr (AutoGenerated::FlagCompileTime::use_mpi)
    {
#ifndef NO_MPI
      std::atexit(WrapMPI::finalize);
#endif
    }

    info.current_rank = static_cast<size_t>(rank);
    info.n_rank = static_cast<size_t>(size);

    info.thread_per_process = Kokkos::num_threads();

    const auto id_seed = (force_run_id.has_value())
                             ? *force_run_id
                             : static_cast<size_t>(time(nullptr) * info.n_rank
                                                   * info.thread_per_process);

    std::string s = std::to_string(id_seed);
    info.run_id = std::hash<std::string>{}(s);

    return info;
  }

} // namespace Core
