#include "cma_utils/alias.hpp"
#include <host_export_handler.hpp>
#include <impl_post_process.hpp>
#include <iostream>

#ifndef NO_MPI
#  include <mpi_w/wrap_mpi.hpp>
#endif

#ifndef NO_MPI
#  define SEND_MPI_SIG_DUMP                                                    \
    if constexpr (AutoGenerated::FlagCompileTime::use_mpi)                     \
    {                                                                          \
      WrapMPI::host_dispatch(exec, WrapMPI::SIGNALS::DUMP);                    \
    }
#else
#  define SEND_MPI_SIG_DUMP
#endif

void
ExportHandler::pre_post_export(
    const double current_time,
    const Simulation::SimulationUnit& simulation,
    const CmaUtils::TransitionnerPtrType& transitioner)
{
  // Retrieve the current reactor state from the transitioner
  const auto& current_reactor_state = transitioner->get_current();

  // Get gas concentration from the simulation; if available, also get the gas
  // volume

  const auto gas_concentration = simulation.getCgasData();
  std::optional<std::span<const double>> gas_volume = std::nullopt;
  if (current_reactor_state->has_gas())
  {
    auto gv = current_reactor_state->get_gas()->volume();
    gas_volume
        = (!gas_concentration.has_value() || !current_reactor_state->has_gas())
              ? std::nullopt
              : std::make_optional(gv);
  }

  // Update the main exporter with the current simulation data
  main_exporter->update_fields(current_time,
                               simulation.getCliqData(),
                               current_reactor_state->get_liquid()->volume(),
                               gas_concentration,
                               gas_volume,
                               simulation.getMTRData());
}

ExportHandler::ExportHandler(std::shared_ptr<Core::MainExporter> _main_exporter,
                             ExecInfo _exec,
                             size_t _dump_interval,
                             size_t _n_iter_simulation)
    : dump_interval(_dump_interval), n_iter_simulation(_n_iter_simulation),
      exec(_exec), main_exporter(std::move(_main_exporter))
{
}

bool
ExportHandler::operator()(double current_time,
                          size_t loop_counter,
                          Simulation::SimulationUnit& simulation,
                          Core::PartialExporter& partial_exporter,
                          const CmaUtils::TransitionnerPtrType& transitioner)
{

  // Only proceed if the dump interval is reached
  if (++dump_counter != dump_interval)
  {
    return false;
  }
  // Declare profiling here to count only if we actually export
  PROFILE_SECTION("host:handle_export")

  // Retrieve the current simulation state
  const auto& state = transitioner->get_current();

  // Send MPI dump signal
  SEND_MPI_SIG_DUMP
  std::optional<std::span<const double>> volume_gas = std::nullopt;
  if (state->has_gas())
  {
    volume_gas = state->get_gas()->volume();
  }

  // Update progress bar if verbose mode is enabled
  if constexpr (AutoGenerated::FlagCompileTime::verbose)
  {
    progressbar.show(std::cout, n_iter_simulation, loop_counter);
  }

  // Update main exporter with current simulation data
  main_exporter->update_fields(current_time,
                               simulation.getCliqData(),
                               state->get_liquid()->volume(),
                               simulation.getCgasData(),
                               volume_gas,
                               simulation.getMTRData());

  // Clear event counter if enabled
  if constexpr (AutoGenerated::FlagCompileTime::enable_event_counter)
  {
    partial_exporter.write_tally(simulation.mc_unit->events.get_span());
    simulation.mc_unit->events.clear();
  }

  // Write particle repartition
  partial_exporter.write_number_particle(simulation.mc_unit->getRepartition());

  // Save probes and particle state if enabled
  if constexpr (AutoGenerated::FlagCompileTime::use_probe)
  {
    PostProcessing::save_probes(simulation, partial_exporter);
  }
  if constexpr (AutoGenerated::FlagCompileTime::dump_particle_state)
  {
    PostProcessing::save_particle_state(simulation, partial_exporter);
  }

  // Reset dump counter
  dump_counter = 0;
  return true;
}
