#include <Kokkos_Core.hpp>
#include <Kokkos_ScatterView.hpp>
#include <biocma_cst_config.hpp>
#include <common/execinfo.hpp>
#include <common/logger.hpp>
#include <core/post_process.hpp>
#include <dataexporter/data_exporter.hpp>
#include <impl_post_process.hpp>
#include <mc/traits.hpp>
#include <mc/unit.hpp>
#include <memory>
#include <numeric>
#include <optional>
#include <simulation/probe.hpp>
#include <simulation/simulation_getter.hpp>
#include <variant>

namespace
{
  void append_properties(int counter,
                         const std::unique_ptr<MC::MonteCarloUnit>& mc_unit,
                         Core::PartialExporter& partial_exporter,
                         bool with_age);

  template <std::size_t buffer_size>
  void
  _save_probes(Simulation::ProbeType ptype,
               const Simulation::Probes<buffer_size>& probes,
               Core::PartialExporter& pde,
               bool force)
  {
    // TODO: Find out if comment is necessary or not
    if (probes.need_export() || force)
    {
      // Ignore array warning because ProbeType is size of probes by
      // construction

      //  NOLINTBEGIN(cppcoreguidelines-pro-bounds-constant-array-index))
      const auto& probe_name
          = Simulation::map_probe_name[static_cast<std::size_t>(ptype)];
      // NOLINTEND(cppcoreguidelines-pro-bounds-constant-array-index))
      //

      // probe.get only returns the used chunk of memory i.e:
      // buffer_size if need export else internal counter
      pde.write_probe(probe_name, probes.get());

      probes.clear();
    }
  }
} // namespace

namespace PostProcessing
{

  void
  save_probes(const Simulation::Getter& getter,
              Core::PartialExporter& pde,
              bool force)
  {

    // WARN: const everywhere but _save_probes modifies
    // internal probe state
    for (const auto& [ptype, probes] : getter.it_probes())
    {
      _save_probes(ptype, probes, pde, force);
    }
  }
  static int counter
      = 0; // TODO Remove static and reset to 0 when new simulation. If handle
           // is reused for two simulation as itś static counter is not reset

  void
  save_particle_state(const Simulation::Getter& getter,
                      Core::PartialExporter& pde)
  {
    if (getter.mc_unit()->n_particle() != 0)
    {
      ::append_properties(
          counter,
          getter.mc_unit(),
          pde,
          AutoGenerated::PostProcessing::FlagCompileTime::export_age);
      counter++;
    }
  }

  void
  final_post_processing(
      const std::shared_ptr<IO::Logger>& logger,
      [[maybe_unused]] const ExecInfo& exec,
      [[maybe_unused]] const Core::SimulationParameters& params,
      const Simulation::Getter& getter,
      const std::shared_ptr<Core::MainExporter>& mde)
  {

    if (logger)
    {
      logger->print("Post Processing", "Saving final results...");
    }
    const auto& mc_unit = *getter.mc_unit();

    mde->write_final(getter, mc_unit.n_particle());
    // v1.2: Remove was useless
    //
    //  if constexpr (AutoGenerated::FlagCompileTime::enable_event_counter)
    //  {
    //    auto removed = mc_unit.events.get_cumulative<MC::EventType::Death>()
    //                   + mc_unit.events.get_cumulative<MC::EventType::Exit>();
    //    auto new_p =
    //    mc_unit.events.get_cumulative<MC::EventType::NewParticle>(); auto
    //    distribution = mc_unit.getRepartition(); auto tot = std::accumulate(
    //        distribution.begin(), distribution.end(), static_cast<size_t>(0));
    //    mc_unit.events.clear();
    //    std::size_t balance = new_p - removed + params.number_particle;
    //    if (tot != balance)
    //    {
    //      if (logger)
    //      {
    //        logger->alert(
    //            "Post Processing",

    //           IO::format("Results are not coherent (Bad particle balance): ",
    //                      tot,
    //                      "=",
    //                      new_p,
    //                      "-",
    //                      removed,
    //                      "+",
    //                      params.number_particle));
    //     }
    //   }
    // }
  }

  void
  show_sumup_state(const std::shared_ptr<IO::Logger>& logger,
                   const Simulation::Getter& getter) noexcept
  {
    if (logger)
    {
      for (auto&& c : getter.mc_unit()->getRepartition())
      {
        logger->raw_log(IO::format(std::to_string(c), " "));
      }
      logger->raw_log("\r\n");
    }
  }

  void
  reset_counter()
  {
    counter = 0;
  }

} // namespace PostProcessing

namespace
{

  std::optional<PostProcessing::BonceBuffer> get_particle_properties_device(
      const std::unique_ptr<MC::MonteCarloUnit>& mc_unit, bool with_age);

  void
  append_properties(const int counter,
                    const std::unique_ptr<MC::MonteCarloUnit>& mc_unit,
                    Core::PartialExporter& partial_exporter,
                    const bool with_age)
  {
    constexpr bool compress_data
        = AutoGenerated::PostProcessing::FlagCompileTime::compress_export;
    auto dump = get_particle_properties_device(mc_unit, with_age);
    if (dump.has_value())
    {
      std::string ds_name = "biological_model/" + std::to_string(counter) + "/";
      partial_exporter.write_particle_data(
          std::move(*dump), ds_name, compress_data);
    }
  }

  std::optional<PostProcessing::BonceBuffer>
  get_particle_properties_device(
      const std::unique_ptr<MC::MonteCarloUnit>& mc_unit, bool with_age)
  {

    // BonceBuffer properties;
    const size_t n_compartment = mc_unit->domain.getNumberCompartments();

    return std::visit(
        [n_compartment, with_age](auto& container)
        {
          using CurrentModel = typename std::remove_reference<
              decltype(container)>::type::UsedModel;
          return PostProcessing::get_properties<CurrentModel>(
              container, n_compartment, with_age);
        },
        mc_unit->container);
  }

} // namespace
