#include "biocma_cst_config.hpp"
#include "common/logger.hpp"
#include "mc/traits.hpp"
#include <Kokkos_Core.hpp>
#include <Kokkos_ScatterView.hpp>
#include <common/execinfo.hpp>
#include <core/post_process.hpp>
#include <dataexporter/data_exporter.hpp>
#include <impl_post_process.hpp>
#include <mc/unit.hpp>
#include <memory>
#include <numeric>
#include <optional>
#include <simulation/simulation.hpp>
#include <variant>
namespace
{
  void append_properties(int counter,
                         Simulation::SimulationUnit& simulation,
                         Core::PartialExporter& partial_exporter,
                         bool with_age);
} // namespace

namespace PostProcessing
{

  void save_probes(Simulation::SimulationUnit& simulation,
                   Core::PartialExporter& pde,
                   bool force)
  {
    auto& probes = simulation.get_probes();

    // TODO: Find out if comment is necessary or not
    if (probes.need_export() || force)
    {
      pde.write_probe(
          probes.get()); // probe.get only returns the used chunk of memory id:
                         // buffer_size if need export else internal counter
      probes.clear();
    }
  }
  static int counter =
      0; // TODO Remove static and reset to 0 when new simulation. If handle is
         // reused for two simulation as itś static counter is not reset

  void save_particle_state(Simulation::SimulationUnit& simulation,
                           Core::PartialExporter& pde)
  {
    const bool with_age = true; // TODO
    ::append_properties(counter, simulation, pde, with_age);
    counter++;
  }

  void final_post_processing(const std::shared_ptr<IO::Logger>& logger,
                             [[maybe_unused]] const ExecInfo& exec,
                             const Core::SimulationParameters& params,
                             Simulation::SimulationUnit& simulation,
                             const std::shared_ptr<Core::MainExporter>& mde)
  {
    if (logger)
    {
      logger->print("Post Processing", "Saving final results...");
    }

    mde->write_final(simulation, simulation.mc_unit->n_particle());

    if constexpr (AutoGenerated::FlagCompileTime::enable_event_counter)
    {
      auto removed = simulation.mc_unit->events.get<MC::EventType::Death>() +
                     simulation.mc_unit->events.get<MC::EventType::Exit>();
      auto new_p = simulation.mc_unit->events.get<MC::EventType::NewParticle>();
      auto distribution = simulation.mc_unit->getRepartition();
      auto tot = std::accumulate(
          distribution.begin(), distribution.end(), static_cast<size_t>(0));
      if (tot != (new_p - removed + params.number_particle))
      {
        if (logger)
        {

          logger->alert(
              "Post Processing",
              IO::format("Results are not coherent (Bad particle balance): ",
                         std::to_string(tot),
                         "=",
                         std::to_string(new_p),
                         "-",
                         std::to_string(removed),
                         "+",
                         std::to_string(params.number_particle)));
        }
      }
    }
  }

  void show_sumup_state(const std::shared_ptr<IO::Logger>& logger,
                        const Simulation::SimulationUnit& simulation) noexcept
  {
    if (logger)
    {
      for (auto&& c : simulation.mc_unit->getRepartition())
      {
        logger->raw_log(IO::format(std::to_string(c), " "));
      }
      logger->raw_log("\r\n");
    }
  }

  void reset_counter()
  {
    counter = 0;
  }

} // namespace PostProcessing

namespace
{

  std::optional<PostProcessing::BonceBuffer> get_particle_properties_device(
      const std::unique_ptr<MC::MonteCarloUnit>& mc_unit, bool with_age);

  void append_properties(const int counter,
                         Simulation::SimulationUnit& simulation,
                         Core::PartialExporter& partial_exporter,
                         const bool with_age)
  {
    bool compress_data = false;
    auto dump = get_particle_properties_device(simulation.mc_unit, with_age);
    if (dump.has_value())
    {
      std::string ds_name = "biological_model/" + std::to_string(counter) + "/";
      partial_exporter.write_particle_data(
          std::move(*dump), ds_name, compress_data);
    }
  }

  std::optional<PostProcessing::BonceBuffer> get_particle_properties_device(
      const std::unique_ptr<MC::MonteCarloUnit>& mc_unit, bool with_age)
  {

    // BonceBuffer properties;
    const size_t n_compartment = mc_unit->domain.getNumberCompartments();

    return std::visit(
        [n_compartment, with_age](auto& container)
        {
          using CurrentModel = typename std::remove_reference<
              decltype(container)>::type::UsedModel;
          return PostProcessing::get_properties<CurrentModel>(
              container, n_compartment, with_age);
        },
        mc_unit->container);
  }

} // namespace

// #include <stdio.h>
// #include <string_view>

// template <int N>
// constexpr void float_to_char(float value, char result[N]) {
//     int int_part = static_cast<int>(value);
//     int frac_part = static_cast<int>((value - int_part) * 100);
//     int index = 0;
//     if (int_part == 0) {
//         result[index++] = '0';
//         result[index++] = '0';
//     } else {
//         int temp = int_part;

//         while (temp > 0) {
//             result[index++] = '0' + temp % 10;
//             temp /= 10;
//         }
//         if (int_part < 10) {
//             result[index++] = '0';
//         }

//         for (int i = 0; i < index / 2; ++i) {
//             char tmp = result[i];
//             result[i] = result[index - 1 - i];
//             result[index - 1 - i] = tmp;
//         }
//     }

//     result[index++] = '.';
//     result[index++] = '0' + (frac_part / 10);
//     result[index++] = '0' + (frac_part % 10);
// }

// template <int N>
// constexpr void fill(char arr[N]) {
//     for (int i = 0; i < N - 1; ++i) {
//         arr[i] = ' ';
//     }
//     arr[N] = '\0';
// }

// template<int PROGRESS_BAR_WIDTH,char PROGRESS_BAR_SYMBOL>
// class ProgressBar {
//    public:
//     constexpr ProgressBar(std::size_t _total):total(_total) {
//         constexpr auto offset = PROGRESS_BAR_WIDTH + init_size;

//         fill<total_bar_width>(bar_buffer);
//         fill<percentage_size>(percentage);

//         bar_buffer[0] = '[';

//         bar_buffer[offset + 1] = ']';
//         bar_buffer[total_bar_width - 1] = '%';

//         for (int i = 0; i < init.size(); ++i) {
//             bar_buffer[i] = init[i];
//         }
//     }

//     // ProgressBar(std::size_t _total,void* tag) {
//     //     constexpr auto offset = PROGRESS_BAR_WIDTH + init_size;

//     //     fill<total_bar_width>(bar_buffer);
//     //     fill<percentage_size>(percentage);

//     //     bar_buffer[0] = '[';

//     //     bar_buffer[offset + 1] = ']';
//     //     bar_buffer[total_bar_width - 1] = '%';

//     //     for (int i = 0; i < init.size(); ++i) {
//     //         bar_buffer[i] = init[i];
//     //     }
//     // }

//    constexpr void update(std::size_t current_position) {
//         const size_t progress = (current_position * PROGRESS_BAR_WIDTH) /
//         (total-1); const float f = (static_cast<float>(current_position) *
//         100.0f /
//                          static_cast<float>(total-1));
//         int current = init_size;
//         for (; current < init_size+progress+1;++current) {
//             bar_buffer[current] = PROGRESS_BAR_SYMBOL;
//         }

//         float_to_char<percentage_size>(f, percentage);
//         // auto* ptr_c = &bar_buffer[percentage_position + 1];
//         // auto* ptr_p = &percentage[0];
//         // const auto* const p_end = &percentage[percentage_size];
//         // while(ptr_p!=p_end){
//         //     *(ptr_c++) = *(ptr_p++);
//         // }
//         current = percentage_position + 1;
//         for(int i=0;i<percentage_size;++i,++current){
//             bar_buffer[current]=percentage[i];
//         }
//     }

//     void show(FILE* stream)
//     {
//         fprintf(stream,"%s\r\n",bar_buffer);
//         fflush(stream);
//     }

//     const char* const get() const { return bar_buffer; }

//    private:
//     static constexpr std::string_view init = "Progress: [";
//     static constexpr auto init_size = init.size();
//     static constexpr size_t percentage_size = 6;
//     static constexpr std::size_t total_bar_width = PROGRESS_BAR_WIDTH +
//     init_size + 2 + percentage_size + 1 + 1;; static constexpr size_t
//     percentage_position = init_size + PROGRESS_BAR_WIDTH + 2;

//     char percentage[percentage_size + 1] = {};

//     // static constexpr size_t total_bar_width = buffer_size();

//     char bar_buffer[total_bar_width + 1] = {};
//     std::size_t total;
// };

// void __attribute__((noinline)) foo(volatile int* a)
// {
//     volatile int* b = a;
//     __asm__ volatile ("nop" : : : "memory");
// }

// int main() {
//     constexpr auto total = 10;
//     constexpr size_t _PROGRESS_BAR_WIDTH = 10;
//     constexpr char _PROGRESS_BAR_SYMBOL = 'x';
//     ProgressBar<_PROGRESS_BAR_WIDTH,_PROGRESS_BAR_SYMBOL> p(total);
//     const auto* const ptr = p.get();
//     volatile int a =1;
//     constexpr auto ii =1 ;
//     FILE* stream = stdout;
//     for (int i = 0; i < total; ++i) {
//         foo(&a);
//         p.update(i);
//         p.show(stream);
//     }

//     return ptr[0];
// }
