name: CI

on:
  push:
    branches:
      - main  
      - v0/**
  pull_request:
    branches:
      - main  

jobs:
  get_dependencies_gcc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      # - name: Setup Cpp (C++ / C)
      #   uses: aminya/setup-cpp@v0.37.0
      #   with:
      #     compiler: 'gcc' 
      #     ninja: true
      #     meson: true
      #     python: true
      #     make: false
      #     doxygen: false

      # - name: Install Pybind11
      #   run: pip install pybind11

  build_gcc_cma_read:
    runs-on: ubuntu-latest
    needs: get_dependencies_gcc
    steps:
      - name: Configure and build project
        run: |
          ls  
          cd subprojects/CMA_reader
          
  #        mkdir build
   #       meson setup build
    #      meson compile -C build
     #     cd ../

  build_app_gcc:
    runs-on: ubuntu-latest
    needs: build_gcc_cma_read
    steps:
      - name: Configure and build project
        run: |
          mkdir 
          meson setup builddir/ --buildtype=release 
          meson compile -C build
  testing_gcc:
    runs-on: ubuntu-latest
    needs: build_app_gcc
    steps:
      - name: Run unit tests
        run: |
          cd CMA_reader/build
          meson test
