name: CI
'on':
  push:
    branches:
      - main
      - v0/**
      - poc/**
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps:


      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT_TOKEN }}'

      - name: Clone GitLab submodule
        run: |
            git config --global credential.helper '!f() { echo "username=${{ secrets.USER_GITLAB }}"; echo "password=${{ secrets.PAT_GITLAB }}"; }; f'
            git submodule update --init --recursive
            ls subprojects/birem
            ls /usr/local/include

      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.37.0
        with:
          compiler: gcc
          ninja: true
          meson: false # Use custom instead 
          python: false # Use custom instead 
          make: false 
          doxygen: false
      

      - name: OMP / MPI / Dependencies
        run: sudo apt-get install -y libomp-dev libopenmpi-dev libeigen3-dev 
      - name: Install Python Development Packages
        run:  sudo apt-get install -y python3-dev python3 python3-pybind11 python3-pip
      - name: Install Meson 
        run: pip3 install meson 
      - name: Configure and build project
        run: |
          mkdir builddir
          meson setup builddir/ --buildtype=release
          meson compile -C builddir
      - name: Run unit tests
        run: |
          cd builddir
          meson test
