name: containerized_test
'on':
  push:
    branches:
      - main
      - dev/0.0.4/**
  pull_request:
    branches:
      - main

jobs:
  Build_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: '${{ secrets.PAT_TOKEN }}'
    - name: Clone GitLab submodule
      run: >
        git config --global credential.helper '!f() { echo "username=${{
        secrets.USER_GITLAB }}"; echo "password=${{ secrets.PAT_GITLAB }}"; };
        f'

        git submodule update --init --recursive
    - name: prepare 
      run: > 
      mkdir -p ./devutils/docker/runtime_container
      mkdir -p ./cma_data
    - name: build
      uses: hoverkraft-tech/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
        services: | 
          app 
        