name: build-image

on:
  push:
    branches:
      - main
      - dev/0.8*
  pull_request:
    branches:
      - main
      - dev/0.8-docker

permissions:
  contents: read
  packages: write

jobs:
  build-docker-base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: biocma_omp_base
            context: ./devutils/docker
            dockerfile: ./devutils/docker/Dockerfile.omp-base
            tag: biocma_omp_base:latest
            output: /tmp/biocma_omp_base.tar

          # - name: biocma_cuda_base
          #   context: ./devutils/docker
          #   dockerfile: ./devutils/docker/Dockerfile.cuda-base
          #   tag: biocma_cuda_base:latest
          #   output: /tmp/biocma_cuda_base.tar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT_TOKEN }}'
          submodules: recursive

      - name: Clone GitLab submodule
        run: |
          git config --global credential.helper '!f() { echo "username=${{ secrets.USER_GITLAB }}"; echo "password=${{ secrets.PAT_GITLAB }}"; }; f'
          git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (${{ matrix.image.name }})
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          tags: ${{ matrix.image.tag }}
          outputs: type=docker,dest=${{ matrix.image.output }}

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.name }}
          path: ${{ matrix.image.output }}

  build-docker-dependent-image:
    runs-on: ubuntu-latest
    needs: build-docker-base-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT_TOKEN }}'
          submodules: recursive

      - name: Clone GitLab submodule
        run: |
          git config --global credential.helper '!f() { echo "username=${{ secrets.USER_GITLAB }}"; echo "password=${{ secrets.PAT_GITLAB }}"; }; f'
          git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Docker base image artifact
        uses: actions/download-artifact@v4
        with:
          name: biocma_omp_base
          path: /tmp

      - name: Load Docker base image
        run: docker load --input /tmp/biocma_omp_base.tar

      # - name: Build Docker dependent image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./devutils/docker/Dockerfile.omp_rls
      #     tags: biocma_omp_rls:latest
      #     outputs: type=docker,dest=/tmp/biocma_omp_rls.tar
      - name: Build Docker image
        run: docker build -t biocma_omp -f ./devutils/docker/Dockerfile.omp_rls .

      - name: Save Docker image
        run: docker save biocma_omp -o /tmp/biocma_omp.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: biocma_omp
          path: /tmp/biocma_omp.tar




