name: Format

'on':
  push:
    branches:
      - main
      - v0/**
      - poc/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  clang-tidy:
    # When making changes here, please also review the "Clang-Tidy" section
    # in .github/CONTRIBUTING.md and update as needed.
    name: Clang-Tidy
    runs-on: ubuntu-latest
    container: silkeh/clang:15-bullseye
    steps:
    - uses: actions/checkout@v4

    - name: install Python
      run: sudo apt update -q && sudo apt-get install -y python3-dev python3 python3-pip

    - name: get LLVM clang-tidy/clang-format
      run: |
        sudo sh devutils/clang_config.sh

    - name: Install Meson 
      run: pip install meson 

    - name: Configure project
      run: |
          mkdir builddir
          meson setup builddir/ --buildtype=release
    
    - name: format
      run: | 
        ninja -C builddir/ clang-format 
    - name: Clang-Tidy
      run: | 
        ninja -C builddir/ clang-tidy 

