name: Format

on: [push, pull_request]
permissions:
  contents: read
jobs:
  python-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: check --output-format=github . --exit-zero

  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: get LLVM clang-tidy/clang-format
        run: |
          sudo sh devutils/docker/clang_config.sh 17
      - name: Configure project
        run: |
          meson setup builddir/ --buildtype=release 
      - name: Clang-Tidy
        run: |
          ninja -C builddir clang-tidy 

