name: Format

on: [push, pull_request]
permissions:
  contents: read
jobs:
  python-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .

  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: get LLVM clang-tidy/clang-format
        run: |
          sudo sh devutils/clang_config.sh 17
      - name: Configure project
        run: |
          meson setup builddir/ --buildtype=release -Dcpp_std=gnu++20
      - name: Clang-Tidy
        run: |
          ninja -C builddir clang-tidy 

