name: Format

'on':
  push:
    branches:
      - main
      - v0/**
      - poc/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  clang-tidy-format:

    name: Clang-Tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install Python
      run: sudo apt update -q && sudo apt-get install -y python3-dev python3 python3-pip 
    - name: install dependencies
      run: sudo apt-get install -y  libomp-dev libopenmpi-dev libeigen3-dev pkg-config

    - name: get LLVM clang-tidy/clang-format
      run: |
        sudo sh devutils/clang_config.sh

    - name: Install Meson 
      run: pip install meson 

    - name: Configure project
      run: |
          mkdir builddir
          meson setup builddir/ --buildtype=release
    
    - name: format
      run: | 
        ninja -C builddir/ clang-format 
    - name: Clang-Tidy
      run: | 
        ninja -C builddir/ clang-tidy 

