name: build_test
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

permissions:
  contents: read  
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: '${{ runner.name }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.PAT_TOKEN }}'
      - name: Clone GitLab submodule
        run: >
          git config --global credential.helper '!f() { echo "username=${{
          secrets.USER_GITLAB }}"; echo "password=${{ secrets.PAT_GITLAB }}"; };
          f'

          git submodule update --init --recursive
      - name: get dependencies
        run: |
          sudo sh devutils/install_dep.sh
      - name: Configure project
        run: |
          mkdir builddir
          meson setup builddir/ --buildtype=release 
      - name: Build project
        run: ninja -k 1 -C builddir
      # - name: Run unit tests
      #   run: |
      #     meson test -C builddir



